<?php
/**
 * @file
 * Add link to archived pdf articles of Ting objects.
 */

// Load Field module hooks.
module_load_include('inc', 'artesis_netarchive', 'artesis_netarchive.field');

/**
 * Implements hook_menu().
 */
function artesis_netarchive_menu() {
  $items = array();

  $items['ting/netarchive'] = array(
    'title' => 'Retreives netarchive for Ting objects',
    'page callback' => 'artesis_netarchive_objects',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'artesis_netarchive.pages.inc',
  );

  $items['netarchive'] = array(
    'title' => 'Create Netarchive field.',
    'page callback' => 'artesis_netarchive_new_field',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function artesis_netarchive_theme() {
  return array(
    'artesis_netarchive_link_theme' => array(
      'render element' => 'elements',
      'file' => 'artesis_netarchive.theme.inc',
    ),
  );
}

function artesis_netarchive_new_field() {

}
