<?php
/**
 * @file
 * Add link to archived pdf articles of Ting objects.
 */

// Load Field module hooks.
module_load_include('inc', 'artesis_netarchive', 'artesis_netarchive.field');

/**
 * Implements hook_menu().
 */
function artesis_netarchive_menu() {
  $items = array();

  $items['ting/netarchive'] = array(
    'title' => 'Retreives netarchive for Ting objects',
    'page callback' => 'artesis_netarchive_objects',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'artesis_netarchive.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function artesis_netarchive_theme() {
  return array(
    'artesis_netarchive_link_theme' => array(
      'render element' => 'elements',
      'file' => 'artesis_netarchive.theme.inc',
    ),
  );
}

/**
 * Implements hook_preprocess_ting_object().
 *
 * Force the field to appear above the ding_entity_buttons.
 */
function artesis_netarchive_preprocess_ting_object(&$variables) {
  // Dive in only for 'search_result' view mode.
  if ('search_result' !== $variables['elements']['#view_mode']) {
    return;
  }

  $content = &$variables['content'];

  if (empty($content['group_content'])) {
    return;
  }

  $buttons_position = array_search(
    'ding_entity_buttons',
    array_keys($content['group_content'])
  );
  // Do nothing if the 'ding_entity_buttons' field is not found in the
  // 'group_content' fieldgroup or the 'netarchive_link' field is
  // hidden or assigned to another group via field ui.
  if (FALSE === $buttons_position || empty($content['netarchive_link'])) {
    return;
  }

  // Hacky way to override field ui settings and force the field to appear
  // above the entity buttons.
  $netarchive_field = $content['netarchive_link'];
  unset($content['netarchive_link']);
  // Since 'array_splice' fails to insert items on N-th position for
  // associative arrays, use this approach.
  $content['group_content'] = array_slice($content['group_content'], 0 , $buttons_position, TRUE) +
    ['netarchive_link' => $netarchive_field] +
    array_slice($content['group_content'], $buttons_position, NULL, TRUE);
}
